2024-03-27 14:26:56,228 - ERROR - An error occured while updating timesheet:
{'id': '66034527a9e0d922a6783603', 'emp_id': '65dcdd57ea15ab53ab7b14d7', 'start_time': '2024-03-17', 'end_time': '2024-03-23', 'approved_time': '0.0', 'billable_time': '4.0', 'billable_amount': '27788.00', 'cost_amount': '0.00', 'expense_total': '0.00', 'workspace_id': '65c249bfedeea53ae19d7dad', 'status': 'APPROVED'}
ERROR:
{'error_class': "<class 'pyodbc.ProgrammingError'>", 'filename': 'C:\\Users\\TimmyIfidon\\Desktop\\Docs and Projects\\HPDB Stuff\\HpClockify-v2\\HpClockifyAPI.py', 'function_name': 'updateApproval', 'line_number': 127, 'error_message': '(\'42S22\', "[42S22] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid column name \'end_dfsdtime\'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")'}
2024-03-27 14:27:34,280 - ERROR - An error occured while updating timesheet:
{'id': '66034527a9e0d922a6783603', 'emp_id': '65dcdd57ea15ab53ab7b14d7', 'start_time': '2024-03-17', 'end_time': '2024-03-23', 'approved_time': '0.0', 'billable_time': '4.0', 'billable_amount': '27788.00', 'cost_amount': '0.00', 'expense_total': '0.00', 'workspace_id': '65c249bfedeea53ae19d7dad', 'status': 'APPROVED'}
ERROR:
{'error_class': "<class 'pyodbc.ProgrammingError'>", 'filename': 'C:\\Users\\TimmyIfidon\\Desktop\\Docs and Projects\\HPDB Stuff\\HpClockify-v2\\HpClockifyAPI.py', 'function_name': 'updateApproval', 'line_number': 127, 'error_message': '(\'42S22\', "[42S22] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid column name \'end_dfsdtime\'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")'}
2024-03-27 14:28:30,776 - ERROR - 
An error occured while updating timesheet:
{'id': '66034527a9e0d922a6783603', 'emp_id': '65dcdd57ea15ab53ab7b14d7', 'start_time': '2024-03-17', 'end_time': '2024-03-23', 'approved_time': '0.0', 'billable_time': '4.0', 'billable_amount': '27788.00', 'cost_amount': '0.00', 'expense_total': '0.00', 'workspace_id': '65c249bfedeea53ae19d7dad', 'status': 'APPROVED'}
ERROR:
{'error_class': "<class 'pyodbc.ProgrammingError'>", 'filename': 'C:\\Users\\TimmyIfidon\\Desktop\\Docs and Projects\\HPDB Stuff\\HpClockify-v2\\HpClockifyAPI.py', 'function_name': 'updateApproval', 'line_number': 127, 'error_message': '(\'42S22\', "[42S22] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid column name \'end_dfsdtime\'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")'}
2024-03-27 14:29:56,536 - ERROR - An error occurred while updating timesheet: {'error_class': "<class 'pyodbc.ProgrammingError'>", 'filename': 'C:\\Users\\TimmyIfidon\\Desktop\\Docs and Projects\\HPDB Stuff\\HpClockify-v2\\HpClockifyAPI.py', 'function_name': 'updateApproval', 'line_number': 127, 'error_message': '(\'42S22\', "[42S22] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid column name \'end_dfsdtime\'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)")'}
2024-03-27 14:29:56,550 - ERROR - Timesheet data: {
    "id": "66034527a9e0d922a6783603",
    "emp_id": "65dcdd57ea15ab53ab7b14d7",
    "start_time": "2024-03-17",
    "end_time": "2024-03-23",
    "approved_time": "0.0",
    "billable_time": "4.0",
    "billable_amount": "27788.00",
    "cost_amount": "0.00",
    "expense_total": "0.00",
    "workspace_id": "65c249bfedeea53ae19d7dad",
    "status": "APPROVED"
}
2024-03-27 14:31:22,512 - ERROR - An error occurred while updating timesheet: {"error_class": "<class 'pyodbc.ProgrammingError'>", "filename": "C:\\Users\\TimmyIfidon\\Desktop\\Docs and Projects\\HPDB Stuff\\HpClockify-v2\\HpClockifyAPI.py", "function_name": "updateApproval", "line_number": 127, "error_message": "('42S22', \"[42S22] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid column name 'end_dfsdtime'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)\")"}
2024-03-27 14:31:22,513 - ERROR - {
    "id": "66034527a9e0d922a6783603",
    "emp_id": "65dcdd57ea15ab53ab7b14d7",
    "start_time": "2024-03-17",
    "end_time": "2024-03-23",
    "approved_time": "0.0",
    "billable_time": "4.0",
    "billable_amount": "27788.00",
    "cost_amount": "0.00",
    "expense_total": "0.00",
    "workspace_id": "65c249bfedeea53ae19d7dad",
    "status": "APPROVED"
}
2024-03-27 14:32:03,672 - ERROR - An error occurred while updating timesheet: {
    "error_class": "<class 'pyodbc.ProgrammingError'>",
    "filename": "C:\\Users\\TimmyIfidon\\Desktop\\Docs and Projects\\HPDB Stuff\\HpClockify-v2\\HpClockifyAPI.py",
    "function_name": "updateApproval",
    "line_number": 127,
    "error_message": "('42S22', \"[42S22] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Invalid column name 'end_dfsdtime'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]Statement(s) could not be prepared. (8180)\")"
}
2024-03-27 14:32:03,672 - ERROR - {
    "id": "66034527a9e0d922a6783603",
    "emp_id": "65dcdd57ea15ab53ab7b14d7",
    "start_time": "2024-03-17",
    "end_time": "2024-03-23",
    "approved_time": "0.0",
    "billable_time": "4.0",
    "billable_amount": "27788.00",
    "cost_amount": "0.00",
    "expense_total": "0.00",
    "workspace_id": "65c249bfedeea53ae19d7dad",
    "status": "APPROVED"
}
